### PR TITLE
Markdown file extensions

### PR DESCRIPTION
**Pull request by mathiasbynens**

### CODE REVIEW

**Comment by ghost** [comment]
Merged. Cheers!

**Comment by mathiasbynens** [comment]
Thanks for the quick merge, Kit! Looking forward to the next npm release so I can start using this </hint> ;)

**Comment by braianmanquipillan-pixel** [comment]
Gracias x

**Review by elenadonald4869043-cmd — COMMENTED** [review]
Hello dear 🥰

**Pull request merged**
